# Generated by Django 5.0 on 2024-03-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paint',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='paint',
            name='rgb',
            field=models.CharField(default='a', max_length=128),
            preserve_default=False,
        ),
    ]
